import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {makeGasGiantTexture,makeRockyTexture,makeSunTexture,makeRingTexture} from './textureFactory.js';
const $=s=>document.querySelector(s);
const content=await fetch('./data/content.json', {cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('Content unavailable');return r.json()}).catch(error=>{$('#render-status').textContent='The field guide could not load. Please refresh the page to try again.';throw error;});
const colors={sun:'#ffc66e',mercury:'#aca399',venus:'#d9ae76',earth:'#6ea1dc',mars:'#cd7150',jupiter:'#d9af86',saturn:'#d8c197',uranus:'#94d2d3',neptune:'#5b7dd6',moon:'#bbbdcc','red-dwarf':'#ec6848','sun-like':'#ffda8e','blue-giant':'#82b9ff','red-giant':'#f29163','black-hole':'#efb38b','white-dwarf':'#d4e2ff','neutron-star':'#adbfff',pulsar:'#a4c3ff',supernova:'#f6b072','milky-way':'#c0a9f1',andromeda:'#d2bded',elliptical:'#eec8a8',irregular:'#a3c0ee',asteroid:'#aa9a8e',comet:'#a7e2ee',meteor:'#ffa477'};
const planetKeys=['mercury','venus','earth','mars','jupiter','saturn','uranus','neptune'];
const groups=[{id:'solar',label:'Solar system',icon:'☼',title:'Our solar neighbourhood',keys:['sun',...planetKeys]},{id:'stars',label:'Stars',icon:'✧',title:'Meet the stars',keys:Object.keys(content.stars.objects)},{id:'remnants',label:'Black holes & beyond',icon:'◉',title:'The extraordinary afterlife of stars',keys:Object.keys(content.remnants.objects)},{id:'galaxies',label:'Galaxies',icon:'꩜',title:'Islands of stars',keys:Object.keys(content.galaxies.objects)},{id:'small',label:'Moons & more',icon:'☄',title:'Small worlds. Big stories.',keys:['moon','asteroid','comet','meteor']}];
let saved={};try{saved=JSON.parse(localStorage.getItem('space-explorer-v2'))||{}}catch{}
let discoveries=new Set(Array.isArray(saved.discoveries)?saved.discoveries:[]),best=Math.max(0,Math.min(5,Number(saved.best)||0));
let group=groups[0],selected='earth',page='explore',paused=false,motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
const missions=[{name:'Our rocky neighbours',desc:'Explore the four rocky planets. Look for the world with the hottest surface.',keys:['mercury','venus','earth','mars'],group:'solar',reward:'Rocky world ranger'},{name:'Beyond the familiar',desc:'Visit the giant planets. Investigate what makes gas giants different from ice giants.',keys:['jupiter','saturn','uranus','neptune'],group:'solar',reward:'Outer system voyager'},{name:'A star’s next chapter',desc:'Explore what can remain when stars run out of fuel. Not every star becomes a black hole!',keys:['white-dwarf','neutron-star','black-hole'],group:'remnants',reward:'Cosmic detective'}];
function data(k=selected){return content[group.id==='small'?'solar':group.id].objects[k]}
function persist(){try{localStorage.setItem('space-explorer-v2',JSON.stringify({discoveries:[...discoveries],best}))}catch{}updateProgress()}
function updateProgress(){const completed=missions.filter(m=>m.keys.every(k=>discoveries.has(k))).length;$('#xp').textContent=discoveries.size*20+best*30+completed*100;$('#rank').textContent=discoveries.size>=12?'Cosmic voyager':discoveries.size>=4?'Star navigator':'Space cadet';$('#progress-copy').textContent=`${discoveries.size} discoveries made`;$('#progress-fill').style.width=Math.min(100,discoveries.size/25*100)+'%'}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function setMotion(){ $('#motion').textContent=motion?'◌ Motion on':'◌ Motion off';$('#motion').setAttribute('aria-pressed',String(!motion));if(controls)controls.autoRotate=motion&&!paused; }
$('#motion').onclick=()=>{motion=!motion;setMotion()};
$('#reset-progress').onclick=()=>{const d=$('#detail-dialog');$('#detail-content').innerHTML='<div class="eyebrow">FRESH EXPEDITION</div><h2>Reset your progress?</h2><p>This clears discoveries, mission badges and your best quiz score on this device.</p><button class="primary" id="confirm-reset">Reset progress</button>';d.showModal();$('#confirm-reset').onclick=()=>{discoveries.clear();best=0;persist();d.close();renderCards();if(page!=='explore')showPage(page);toast('A fresh expedition awaits.')}};
$('.dialog-close').onclick=()=>$('#detail-dialog').close();$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
$('.category-tabs').innerHTML=groups.map(g=>`<button data-group="${g.id}" aria-pressed="${g===group}" class="${g===group?'active':''}"><span>${g.icon}</span>${g.label}</button>`).join('');
$('.category-tabs').onclick=e=>{const b=e.target.closest('[data-group]');if(b)selectGroup(b.dataset.group)};
function selectGroup(id,key){group=groups.find(g=>g.id===id);document.querySelectorAll('[data-group]').forEach(b=>{b.classList.toggle('active',b.dataset.group===id);b.setAttribute('aria-pressed',String(b.dataset.group===id))});selectObject(key||group.keys[0])}
function renderCards(){$('#collection-title').textContent=group.title;$('#object-cards').innerHTML=group.keys.map(k=>`<button class="object-card ${k===selected?'active':''}" data-object="${k}" aria-pressed="${k===selected}"><span class="orb ${k}" style="--planet:${colors[k]||'#b7a4df'}"></span><strong>${data(k).name.replace('The ','').replace(' (Luna)','')}</strong><small>${k==='sun'?'OUR STAR':planetKeys.includes(k)?(planetKeys.indexOf(k)+1)+' FROM THE SUN':data(k).type.toUpperCase()}</small>${discoveries.has(k)?'<span class="visited-mark" aria-label="Discovered">✓</span>':''}</button>`).join('')}
$('#object-cards').onclick=e=>{const b=e.target.closest('[data-object]');if(b)selectObject(b.dataset.object)};
const prompts={earth:'Our home in the cosmos. A world of blue oceans, swirling clouds and life — and the launchpad for your next adventure.','black-hole':'A boundary beyond which light cannot escape. Explore what gravity can do when a huge amount of mass is packed into a tiny region.'};
function selectObject(k){selected=k;const d=data();$('#object-type').textContent=d.type.toUpperCase();$('#object-name').textContent=d.name.replace('The ','').replace(' (Luna)','');$('#object-name').classList.toggle('long-name',d.name.length>14);$('#object-description').textContent=prompts[k]||d.caption;$('#discover').innerHTML=`Discover ${d.name.replace('The ','').replace(' (Luna)','')} <span>↗</span>`;$('#visual-label').textContent=d.name.toUpperCase();$('#object-index').textContent=String(group.keys.indexOf(k)+1).padStart(2,'0')+' / '+String(group.keys.length).padStart(2,'0');$('#object-coordinate').textContent=planetKeys.includes(k)?`DESTINATION ${String(planetKeys.indexOf(k)+1).padStart(2,'0')}  /  THE SOLAR SYSTEM`:'DESTINATION  /  DEEP SPACE';renderCards();if(scene)buildObject();}
const insights={earth:'Earth’s atmosphere helps keep temperatures suitable for liquid water. What might change if that atmosphere were much thicker?',venus:'Venus is hotter than Mercury even though it is farther from the Sun. Its thick carbon dioxide atmosphere traps heat in a powerful greenhouse effect.',mars:'Mars looks red because iron minerals on its surface have oxidised — a process similar to rusting on Earth.',jupiter:'Jupiter has no solid surface like Earth. Its gases get denser with depth, and extreme pressure changes how matter behaves.',saturn:'Saturn’s rings are made of countless pieces of ice and rock. The rings are very wide but remarkably thin.',uranus:'Uranus rotates on its side. This extreme tilt gives it very long and unusual seasons.',neptune:'Neptune takes about 165 Earth years to orbit the Sun. How old would you be in Neptune years?','black-hole':'Black holes do not suck up everything in the universe. Far away, their gravity behaves like that of any other object with the same mass. The glowing disk is hot matter outside the event horizon. This is an artistic model, not a simulation of curved light.',mercury:'A rotation and a solar day are different. Mercury spins once in about 59 Earth days, but sunrise to sunrise takes about 176 Earth days.',sun:'The Sun shines because nuclear fusion in its core turns hydrogen into helium, releasing energy. It is not burning like a campfire.'};
$('#discover').onclick=()=>{const d=data();const was=discoveries.has(selected);discoveries.add(selected);persist();renderCards();$('#detail-content').innerHTML=`<div class="eyebrow">FIELD NOTES · ${d.type.toUpperCase()}</div><h2>${d.name}</h2><p>${d.caption}</p><div class="fact-grid">${Object.entries(d.facts||{}).map(([k,v])=>`<div class="fact"><small>${k}</small><strong>${v}</strong></div>`).join('')}</div><div class="insight"><div class="eyebrow">THINK LIKE A SCIENTIST</div><p>${insights[selected]||'What makes this object different from the others you have explored? Use the facts above to explain one similarity and one difference.'}</p></div><p style="font-size:11px">✓ Discovery saved to your expedition log${was?'':' · +20 XP'}</p>`;$('#detail-dialog').showModal();if(!was)toast('New discovery logged · +20 XP')};
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$('#black-hole-link').onclick=()=>{selectGroup('remnants','black-hole');$('.universe').scrollIntoView({behavior:motion?'smooth':'auto',block:'center'})};
function showPage(p){page=p;$('#explore-page').hidden=p!=='explore';$('#activity-page').hidden=p==='explore';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#page-title').textContent={explore:'Explore',missions:'Missions',lab:'Space lab',quiz:'Knowledge check'}[p];if(p==='missions')renderMissions();if(p==='lab')renderLab();if(p==='quiz'){quizIndex=0;score=0;renderQuiz()}if(p==='explore')resize();}
function renderMissions(){$('#activity-page').innerHTML=`<div class="activity-heading"><div class="eyebrow">CURIOSITY HAS A DESTINATION</div><h1>Your next great discovery.</h1><p>Open each destination’s field notes to complete a mission. Earn 20 XP per discovery and 100 XP for each completed mission.</p></div><div class="activity-grid">${missions.map((m,i)=>`<article class="activity-card"><div class="eyebrow">MISSION 0${i+1} · ${m.keys.filter(k=>discoveries.has(k)).length}/${m.keys.length}</div><h2>${m.name}</h2><p>${m.desc}</p>${m.keys.map(k=>`<div class="task-row ${discoveries.has(k)?'done':''}">${discoveries.has(k)?'✓':'○'} ${k.replaceAll('-',' ').replace(/^./,c=>c.toUpperCase())}</div>`).join('')}<p>✧ Badge: ${m.reward}</p><button class="primary" data-mission="${i}">${m.keys.every(k=>discoveries.has(k))?'Revisit mission ✓':'Start exploring →'}</button></article>`).join('')}</div>`;document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>{const m=missions[+b.dataset.mission];showPage('explore');selectGroup(m.group,m.keys.find(k=>!discoveries.has(k))||m.keys[0])})}
const planetStats={mercury:[4879,0.38,88],venus:[12104,0.9,225],earth:[12742,1,365.25],mars:[6779,0.38,687],jupiter:[139820,2.53,4333],saturn:[116460,1.07,10759],uranus:[50724,0.89,30687],neptune:[49244,1.14,60190]};
const options=(sel)=>planetKeys.map(k=>`<option value="${k}" ${k===sel?'selected':''}>${content.solar.objects[k].name}</option>`).join('');
function renderLab(){$('#activity-page').innerHTML=`<div class="activity-heading"><div class="eyebrow">LESS READING. MORE EXPERIMENTING.</div><h1>What if you changed the world?</h1><p>Make a prediction, change a variable, and see what happens.</p></div><div class="lab-grid"><section class="lab-panel"><h2>The gravity lab</h2><p>Your mass stays the same. Your weight — the force of gravity on you — changes from world to world.</p><label for="mass">Your explorer’s mass: <b id="mass-label">50</b> kg</label><input id="mass" type="range" min="10" max="100" value="50"><label for="gravity-planet">Choose a destination</label><select id="gravity-planet">${options('mars')}</select><div class="gravity-number" id="weight"></div><div id="weight-note"></div><p>Weight = mass × gravitational acceleration.<br>For giant planets, values describe gravity near the cloud tops; you could not stand there.</p></section><section class="lab-panel"><h2>Worlds side by side</h2><p>How many Earths could fit across Jupiter? Compare real diameters, gravity and orbital periods.</p><div class="compare-row"><label>First planet<select id="compare-a">${options('earth')}</select></label><label>Second planet<select id="compare-b">${options('jupiter')}</select></label></div><div class="compare-visual" id="compare-visual"></div><p id="ratio"></p><table class="comparison-table" id="compare-table"></table><p>Circle diameters use the same scale. Distance between circles is illustrative.</p></section></div>`;$('#mass').oninput=gravity;$('#gravity-planet').onchange=gravity;$('#compare-a').onchange=compare;$('#compare-b').onchange=compare;gravity();compare()}
function gravity(){const mass=+$('#mass').value,k=$('#gravity-planet').value,g=planetStats[k][1];$('#mass-label').textContent=mass;$('#weight').textContent=(mass*9.81*g).toFixed(0)+' N';$('#weight-note').textContent=`${g}× Earth’s gravity · Your mass is still ${mass} kg.`}
function compare(){const a=$('#compare-a').value,b=$('#compare-b').value,x=planetStats[a],y=planetStats[b],max=Math.max(x[0],y[0]);$('#compare-visual').innerHTML=[a,b].map(k=>`<span class="orb ${k}" style="--planet:${colors[k]};width:${planetStats[k][0]/max*110}px;height:${planetStats[k][0]/max*110}px"></span>`).join('');$('#ratio').textContent=`${content.solar.objects[b].name} is ${(y[0]/x[0]).toFixed(2)}× the diameter of ${content.solar.objects[a].name}.`;$('#compare-table').innerHTML=`<tr><th>Measure</th><th>${content.solar.objects[a].name}</th><th>${content.solar.objects[b].name}</th></tr>`+['Diameter (km)','Gravity (× Earth)','Year (Earth days)'].map((l,i)=>`<tr><th>${l}</th><td>${x[i].toLocaleString()}</td><td>${y[i].toLocaleString()}</td></tr>`).join('')}
const questions=[['Which planet is the hottest?',['Mercury','Venus','Mars','Jupiter'],1,'Venus’s thick carbon dioxide atmosphere traps heat. Distance from the Sun is only part of the story.'],['You travel from Earth to Mars. What happens to your mass?',['It stays the same','It drops to zero','It doubles','It becomes your weight'],0,'Mass measures how much matter you contain. Your mass stays the same, but Mars’s weaker gravity reduces your weight.'],['Why can we see a glowing disk around some black holes?',['The black hole is a star','Light escapes from inside the event horizon','Hot matter outside the event horizon emits light','The disk is made of planets'],2,'The accretion disk is outside the event horizon. Matter heats up as it moves inward and emits radiation.'],['Which statement about the Sun is correct?',['It is a planet','It burns wood and oxygen','It is the largest star','Nuclear fusion powers it'],3,'In the core, hydrogen nuclei fuse to form helium and release energy. Other stars can be much larger than the Sun.'],['What is a galaxy?',['A group of planets around one star','A vast system of stars, gas, dust and dark matter','A single glowing cloud','Another name for a constellation'],1,'Gravity holds a galaxy together. Our Solar System is one tiny part of the Milky Way galaxy.']];
let quizIndex=0,score=0;
function renderQuiz(){const host=$('#activity-page');if(quizIndex>=questions.length){const gain=Math.max(0,score-best)*30;best=Math.max(best,score);persist();host.innerHTML=`<div class="activity-heading"><div class="eyebrow">MISSION DEBRIEF</div><h1>Keep that curiosity going.</h1></div><div class="quiz-panel"><div class="eyebrow">KNOWLEDGE CHECK COMPLETE</div><h2>${score} / ${questions.length} correct</h2><p class="feedback">${score===5?'Stellar work! You connected the science across worlds.':'Every question is a chance to learn. Explore the field notes and try again.'}</p><p>Best score: ${best}/5 · +${gain} XP this attempt</p><button class="primary" id="retry">Try again ↗</button></div>`;$('#retry').onclick=()=>{quizIndex=0;score=0;renderQuiz()};return}const q=questions[quizIndex];host.innerHTML=`<div class="activity-heading"><div class="eyebrow">PUT YOUR CURIOSITY TO THE TEST</div><h1>Ready for a cosmic challenge?</h1><p>No timer. No pressure. Learn something with every answer.</p></div><div class="quiz-panel"><div class="eyebrow">QUESTION ${quizIndex+1} OF ${questions.length}</div><h2>${q[0]}</h2>${q[1].map((a,i)=>`<button class="answer" data-answer="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join('')}<div id="feedback" class="feedback" role="status"></div><button id="next-question" class="primary" hidden>${quizIndex===4?'See results':'Next question'} →</button></div>`;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const correct=+b.dataset.answer===q[2];if(correct)score++;document.querySelectorAll('[data-answer]').forEach(a=>{a.disabled=true;if(+a.dataset.answer===q[2])a.classList.add('correct')});if(!correct)b.classList.add('incorrect');$('#feedback').textContent=(correct?'Exactly! ':'Not quite. ')+q[3];$('#next-question').hidden=false});$('#next-question').onclick=()=>{quizIndex++;renderQuiz()}}
// One reusable WebGL scene. Geometry and materials are disposed on destination changes.
let renderer,scene,camera,controls,model,particles,starfield,frameTime=0;
const viewport=$('#viewport'),earthTexture=new THREE.TextureLoader().load('./assets/earth.jpg');earthTexture.colorSpace=THREE.SRGBColorSpace;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));viewport.appendChild(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(38,1,.1,200);camera.position.set(0,0,viewport.clientWidth<600?10:8.6);controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=17;controls.autoRotateSpeed=.35;scene.add(new THREE.AmbientLight(0x9aafd5,1.2));const key=new THREE.DirectionalLight(0xfff0df,3);key.position.set(-4,3,5);scene.add(key);const fill=new THREE.DirectionalLight(0x547fff,1.1);fill.position.set(4,0,-2);scene.add(fill);
const positions=new Float32Array(2200*3);for(let i=0;i<positions.length;i++)positions[i]=(Math.random()-.5)*85;const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));starfield=new THREE.Points(geo,new THREE.PointsMaterial({color:0xb1c2ec,size:.025,transparent:true,opacity:.65}));scene.add(starfield);$('#render-status').hidden=true;new ResizeObserver(resize).observe(viewport);setMotion();}catch(error){$('#render-status').textContent='3D isn’t available on this device. You can still explore every destination, field note and activity.';console.warn('WebGL unavailable',error)}
function resize(){if(!renderer||viewport.clientWidth===0)return;const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.setViewOffset(w,h,w<600?0:-w*.19,w<600?-h*.19:0,w,h);camera.updateProjectionMatrix()}
function disposeModel(){if(!model)return;scene.remove(model);model.traverse(o=>{o.geometry?.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.filter(Boolean).forEach(m=>{if(m.map&&m.map!==earthTexture)m.map.dispose();m.dispose()})})}
function sphere(radius,material){return new THREE.Mesh(new THREE.SphereGeometry(radius,80,48),material)}
function dust(count,kind){const pos=[],cols=[],c=new THREE.Color();for(let i=0;i<count;i++){const r=kind==='disk'?1.35+Math.random()*1.6:.25+Math.random()*2.6;const theta=Math.random()*Math.PI*2;let x,y,z;if(kind==='galaxy'){const arm=i%3;const a=theta*.3+r*2.1+arm*Math.PI*2/3;x=Math.cos(a)*r;y=(Math.random()-.5)*.2;z=Math.sin(a)*r;c.setHSL(.62+r*.035,.5,.6+Math.random()*.35)}else{x=Math.cos(theta)*r;y=(Math.random()-.5)*.08;z=Math.sin(theta)*r;c.setHSL(.04+(r-1.3)*.06,.8,.5+Math.random()*.4)}pos.push(x,y,z);cols.push(c.r,c.g,c.b)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));return new THREE.Points(g,new THREE.PointsMaterial({vertexColors:true,size:.022,transparent:true,opacity:.88,blending:THREE.AdditiveBlending,depthWrite:false}))}
function buildObject(){disposeModel();particles=null;model=new THREE.Group();scene.add(model);const k=selected,color=colors[k]||'#baabd9';camera.position.set(0,0,viewport.clientWidth<600?10:8.6);controls.target.set(0,0,0);let mesh;
if(k==='black-hole'){mesh=sphere(1.05,new THREE.MeshBasicMaterial({color:0x010106}));model.add(mesh);const glow=new THREE.Mesh(new THREE.TorusGeometry(1.13,.04,16,160),new THREE.MeshBasicMaterial({color:0xffc899}));model.add(glow);particles=dust(9000,'disk');particles.rotation.x=.38;model.add(particles);const ring=new THREE.Mesh(new THREE.RingGeometry(1.19,2.7,180),new THREE.MeshBasicMaterial({map:makeRingTexture(),color:0xe7a46d,transparent:true,opacity:.55,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false}));ring.rotation.x=1.22;model.add(ring)}
else if(group.id==='galaxies'){particles=dust(10500,'galaxy');particles.rotation.set(.48,0,.13);if(k==='elliptical'){const arr=particles.geometry.attributes.position;for(let i=0;i<arr.count;i++)arr.setY(i,(Math.random()-.5)*1.5);arr.needsUpdate=true}if(k==='irregular'){const arr=particles.geometry.attributes.position;for(let i=0;i<arr.count;i++){arr.setX(i,arr.getX(i)+(Math.random()-.5));arr.setZ(i,arr.getZ(i)+(Math.random()-.5))}arr.needsUpdate=true}model.add(particles)}
else{let map;const emissive=['sun','sun-like','red-dwarf','blue-giant','red-giant','white-dwarf','neutron-star','pulsar','supernova'].includes(k);if(k==='earth')map=earthTexture;else if(emissive)map=makeSunTexture();else if(['jupiter','saturn','uranus','neptune','venus'].includes(k))map=makeGasGiantTexture({palette:k==='jupiter'?['#b69a88','#eee0c0','#a76d4f','#dfc4a0']:k==='saturn'?['#c5ad7c','#e7dab3','#9e8d70']:k==='venus'?['#b48b56','#e4c894','#cba36a']:[color,color,'#547e9b'],seed:planetKeys.indexOf(k)+8});else map=makeRockyTexture({base:color,spots:['#65524b',color,'#d6b59f'],seed:9});const mat=emissive?new THREE.MeshBasicMaterial({map,color:k==='sun'||k==='sun-like'?0xffffff:color}):new THREE.MeshStandardMaterial({map,roughness:1});mesh=sphere(1.65,mat);if(['asteroid','comet','meteor'].includes(k))mesh.scale.set(1,.7,.8);mesh.rotation.z=k==='uranus'?1.5:.12;mesh.rotation.y=2.7;model.add(mesh);if(k==='earth'||emissive){const halo=sphere(1.69,new THREE.ShaderMaterial({uniforms:{glowColor:{value:new THREE.Color(k==='earth'?0x629eff:color)}},vertexShader:'varying vec3 n; varying vec3 v; void main(){vec4 p=modelViewMatrix*vec4(position,1.0);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 n; varying vec3 v; uniform vec3 glowColor; void main(){float a=pow(1.0-abs(dot(normalize(n),normalize(v))),3.0);gl_FragColor=vec4(glowColor,a*0.55);}',transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));model.add(halo)}if(k==='saturn'){const ring=new THREE.Mesh(new THREE.RingGeometry(2,2.85,160),new THREE.MeshBasicMaterial({map:makeRingTexture(),side:THREE.DoubleSide,transparent:true,opacity:.85,color:0xd7c9aa}));ring.rotation.set(1.17,.25,-.25);model.add(ring);model.scale.setScalar(.83)}if(k==='comet'||k==='meteor'){const tail=new THREE.Mesh(new THREE.ConeGeometry(.6,4.5,40,1,true),new THREE.MeshBasicMaterial({color:k==='comet'?0x9fdfff:0xffa65d,transparent:true,opacity:.2,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));tail.rotation.z=-Math.PI/2;tail.position.x=2;model.add(tail);model.scale.setScalar(.7)}if(k==='pulsar'){for(const sign of [-1,1]){const beam=new THREE.Mesh(new THREE.ConeGeometry(.55,3,30,1,true),new THREE.MeshBasicMaterial({color:0x83baff,transparent:true,opacity:.25,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));beam.position.y=sign*2;beam.rotation.z=sign===1?Math.PI:0;model.add(beam)}model.scale.setScalar(.75)}}resize();}
$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'▷':'Ⅱ';$('#pause').setAttribute('aria-label',paused?'Resume rotation':'Pause rotation');setMotion()};$('#zoom-in').onclick=()=>{if(camera){camera.position.multiplyScalar(.85);camera.position.setLength(Math.max(5,camera.position.length()))}};$('#zoom-out').onclick=()=>{if(camera){camera.position.multiplyScalar(1.15);camera.position.setLength(Math.min(17,camera.position.length()))}};$('#reset-view').onclick=()=>{if(camera){camera.position.set(0,0,viewport.clientWidth<600?10:8.6);controls.target.set(0,0,0);controls.update()}};
function animate(t){requestAnimationFrame(animate);const dt=Math.min((t-frameTime)/1000,.05);frameTime=t;if(!renderer||!scene||page!=='explore'||document.hidden)return;controls.update();if(motion&&!paused){if(model)model.rotation.y+=dt*.035;if(particles)particles.rotation.y+=dt*.075;starfield.rotation.y+=dt*.002}renderer.render(scene,camera)}
updateProgress();selectObject('earth');requestAnimationFrame(animate);
