export const OBJECTS = [
 {id:'blackhole',name:'Black hole',tag:'LIGHT CANNOT ESCAPE',color:0xffac58,description:'A black hole is a region where gravity is so strong that nothing can escape once it crosses the event horizon. The glowing material is outside that boundary.',facts:['The dark centre in this observation is the black hole’s shadow.','The Event Horizon Telescope linked radio telescopes across Earth to make this image.','M87’s giant black hole is about 55 million light-years away.'],caption:'M87* · radio observation, Event Horizon Telescope Collaboration. Published by NASA.',source:'https://science.nasa.gov/resource/first-image-of-a-black-hole/',scale:'Black holes have many sizes; this model has no fixed scale.'},
 {id:'wormhole',name:'Wormhole',tag:'A WHAT-IF OF THE UNIVERSE',color:0x9d79ff,description:'Imagine a shortcut connecting distant regions of spacetime. Some mathematical ideas allow wormholes, but nobody has observed one. Our glowing tunnel is an imaginative illustration.',facts:['There is no authentic photograph of a wormhole.','A black hole is not a proven shortcut through space.','The opening journey is science-inspired imagination, not a real travel route.'],caption:'Conceptual model · no observed wormholes or real photographs exist.',source:'https://science.nasa.gov/universe/black-holes/',scale:'Hypothetical object · no measured size.'},
 {id:'quasar',name:'Quasar',tag:'A GALAXY’S DAZZLING HEART',color:0x80cfff,description:'A quasar is the brilliant centre of an active galaxy, powered by material falling towards a supermassive black hole. Despite its star-like appearance, it is not a star.',facts:['A foreground galaxy bends the light of RX J1131 into multiple images.','This quasar’s light has travelled for roughly six billion years.','The energy comes from hot material around the black hole, outside the event horizon.'],caption:'RX J1131 · X-ray: NASA/CXC/Univ. of Michigan/R. C. Reis et al.; optical: NASA/STScI. Composite observation.',source:'https://www.nasa.gov/image-article/distant-quasar-rx-j1131/',scale:'RX J1131 is about 6 billion light-years away.'},
 {id:'supernova',name:'Supernova',tag:'A STAR’S EXPLOSIVE FINALE',color:0xff936c,description:'A supernova is a stellar explosion. What remains can become an expanding, intricate cloud of debris. Here, Webb reveals Cassiopeia A: the aftermath of a massive star’s explosion.',facts:['The image shows the remnant, not an explosion happening right now.','Webb sees infrared light that human eyes cannot detect.','The wisps trace material thrown out by the dying star.'],caption:'Cassiopeia A · Webb NIRCam. NASA, ESA, CSA, STScI, D. Milisavljevic (Purdue), T. Temim (Princeton), I. De Looze (Ghent); processing A. Pagan (STScI). Infrared mapped to visible colours.',source:'https://science.nasa.gov/asset/webb/cassiopeia-a-nircam-image/',scale:'Cassiopeia A’s remnant spans roughly 10 light-years.'},
 {id:'nebula',name:'Nebula',tag:'WHERE NEW STORIES BEGIN',color:0xe085cb,description:'A nebula is a cloud of gas and dust. Some are stellar nurseries. In the Pillars of Creation, young stars form inside enormous columns of material.',facts:['These pillars lie about 6,500 light-years away.','Infrared light helps Webb peer through much of the dust.','The bright red points near pillar edges include young stars.'],caption:'Pillars of Creation · Webb NIRCam. NASA, ESA, CSA, STScI; J. DePasquale, A. Koekemoer, A. Pagan (STScI). Infrared mapped to visible colours.',source:'https://science.nasa.gov/asset/webb/pillars-of-creation-nircam-image/',scale:'The Pillars of Creation are about 6,500 light-years away.'}
];
export const SCALES = [
 ['≈ 86 billion soccer pitches','Across Neptune’s orbit · about 9 billion km'],
 ['≈ 53,000 Solar System widths','Imagine a neighbourhood 50 light-years across'],
 ['≈ 2,000 stellar neighbourhoods','A Milky Way about 100,000 light-years across'],
 ['≈ 100 Milky Ways across','Imagine a region 10 million light-years wide'],
 ['≈ 100 galaxy-region widths','Imagine a web region 1 billion light-years wide'],
 ['From stellar remnants to vast clouds','A collection of wonders · objects are not to scale']
];
